use crate::span::Span;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Identifier(String),
    StringLiteral(String),
    IntegerLiteral(i64),
    BooleanLiteral(bool),
    Null,
    If,
    Else,
    For,
    While,
    Do,
    Break,
    Continue,
    Return,
    New,
    Dot,
    Comma,
    Colon,
    Equal,
    EqualEqual,
    FatArrow,
    Bang,
    BangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Plus,
    PlusPlus,
    Minus,
    MinusMinus,
    Star,
    Slash,
    Percent,
    AndAnd,
    OrOr,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Semicolon,
    Eof,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    pub lexeme: String,
}

impl TokenKind {
    pub fn description(&self) -> &'static str {
        match self {
            Self::Identifier(_) => "identifier",
            Self::StringLiteral(_) => "string literal",
            Self::IntegerLiteral(_) => "integer literal",
            Self::BooleanLiteral(_) => "boolean literal",
            Self::Null => "`null`",
            Self::If => "`if`",
            Self::Else => "`else`",
            Self::For => "`for`",
            Self::While => "`while`",
            Self::Do => "`do`",
            Self::Break => "`break`",
            Self::Continue => "`continue`",
            Self::Return => "`return`",
            Self::New => "`new`",
            Self::Dot => "`.`",
            Self::Comma => "`,`",
            Self::Colon => "`:`",
            Self::Equal => "`=`",
            Self::EqualEqual => "`==`",
            Self::FatArrow => "`=>`",
            Self::Bang => "`!`",
            Self::BangEqual => "`!=`",
            Self::Less => "`<`",
            Self::LessEqual => "`<=`",
            Self::Greater => "`>`",
            Self::GreaterEqual => "`>=`",
            Self::Plus => "`+`",
            Self::PlusPlus => "`++`",
            Self::Minus => "`-`",
            Self::MinusMinus => "`--`",
            Self::Star => "`*`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::AndAnd => "`&&`",
            Self::OrOr => "`||`",
            Self::LeftParen => "`(`",
            Self::RightParen => "`)`",
            Self::LeftBrace => "`{`",
            Self::RightBrace => "`}`",
            Self::LeftBracket => "`[`",
            Self::RightBracket => "`]`",
            Self::Semicolon => "`;`",
            Self::Eof => "end of file",
        }
    }
}
