use crate::span::Span;

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TokenKind {
    Identifier(String),
    StringLiteral(String),
    IntegerLiteral(i64),
    LongLiteral(i128),
    DecimalLiteral(String),
    BooleanLiteral(bool),
    Null,
    If,
    Else,
    For,
    While,
    Do,
    Switch,
    When,
    Break,
    Continue,
    Return,
    Void,
    Try,
    Catch,
    Finally,
    Throw,
    New,
    Instanceof,
    Class,
    Interface,
    Extends,
    Implements,
    Public,
    Private,
    Protected,
    Global,
    Static,
    Virtual,
    Abstract,
    Override,
    Final,
    Transient,
    At,
    Dot,
    Comma,
    Colon,
    Question,
    NullCoalesce,
    SafeNavigation,
    Equal,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    PercentEqual,
    AmpersandEqual,
    PipeEqual,
    CaretEqual,
    ShiftLeftEqual,
    ShiftRightEqual,
    UnsignedShiftRightEqual,
    EqualEqual,
    ExactEqual,
    FatArrow,
    Bang,
    BangEqual,
    ExactBangEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    ShiftLeft,
    ShiftRight,
    UnsignedShiftRight,
    Plus,
    PlusPlus,
    Minus,
    MinusMinus,
    Star,
    Slash,
    Percent,
    Tilde,
    Ampersand,
    Pipe,
    Caret,
    AndAnd,
    OrOr,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Semicolon,
    Eof,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    pub lexeme: String,
}

impl TokenKind {
    pub fn description(&self) -> &'static str {
        if let Some(description) = self.value_description() {
            return description;
        }
        if let Some(description) = self.symbol_description() {
            return description;
        }
        match self {
            Self::If => "`if`",
            Self::Else => "`else`",
            Self::For => "`for`",
            Self::While => "`while`",
            Self::Do => "`do`",
            Self::Switch => "`switch`",
            Self::When => "`when`",
            Self::Break => "`break`",
            Self::Continue => "`continue`",
            Self::Return => "`return`",
            Self::Void => "`void`",
            Self::Try => "`try`",
            Self::Catch => "`catch`",
            Self::Finally => "`finally`",
            Self::Throw => "`throw`",
            Self::New => "`new`",
            Self::Instanceof => "`instanceof`",
            Self::Class => "`class`",
            Self::Interface => "`interface`",
            Self::Extends => "`extends`",
            Self::Implements => "`implements`",
            Self::Public => "`public`",
            Self::Private => "`private`",
            Self::Protected => "`protected`",
            Self::Global => "`global`",
            Self::Static => "`static`",
            Self::Virtual => "`virtual`",
            Self::Abstract => "`abstract`",
            Self::Override => "`override`",
            Self::Final => "`final`",
            Self::Transient => "`transient`",
            Self::Eof => "end of file",
            _ => unreachable!("value and symbol tokens have descriptions"),
        }
    }

    fn value_description(&self) -> Option<&'static str> {
        Some(match self {
            Self::Identifier(_) => "identifier",
            Self::StringLiteral(_) => "string literal",
            Self::IntegerLiteral(_) => "integer literal",
            Self::LongLiteral(_) => "Long literal",
            Self::DecimalLiteral(_) => "decimal literal",
            Self::BooleanLiteral(_) => "boolean literal",
            Self::Null => "`null`",
            _ => return None,
        })
    }

    fn symbol_description(&self) -> Option<&'static str> {
        Some(match self {
            Self::At => "`@`",
            Self::Dot => "`.`",
            Self::Comma => "`,`",
            Self::Colon => "`:`",
            Self::Question => "`?`",
            Self::NullCoalesce => "`??`",
            Self::SafeNavigation => "`?.`",
            Self::Equal => "`=`",
            Self::PlusEqual => "`+=`",
            Self::MinusEqual => "`-=`",
            Self::StarEqual => "`*=`",
            Self::SlashEqual => "`/=`",
            Self::PercentEqual => "`%=`",
            Self::AmpersandEqual => "`&=`",
            Self::PipeEqual => "`|=`",
            Self::CaretEqual => "`^=`",
            Self::ShiftLeftEqual => "`<<=`",
            Self::ShiftRightEqual => "`>>=`",
            Self::UnsignedShiftRightEqual => "`>>>=`",
            Self::EqualEqual => "`==`",
            Self::ExactEqual => "`===`",
            Self::FatArrow => "`=>`",
            Self::Bang => "`!`",
            Self::BangEqual => "`!=`",
            Self::ExactBangEqual => "`!==`",
            Self::Less => "`<`",
            Self::LessEqual => "`<=`",
            Self::Greater => "`>`",
            Self::GreaterEqual => "`>=`",
            Self::ShiftLeft => "`<<`",
            Self::ShiftRight => "`>>`",
            Self::UnsignedShiftRight => "`>>>`",
            Self::Plus => "`+`",
            Self::PlusPlus => "`++`",
            Self::Minus => "`-`",
            Self::MinusMinus => "`--`",
            Self::Star => "`*`",
            Self::Slash => "`/`",
            Self::Percent => "`%`",
            Self::Tilde => "`~`",
            Self::Ampersand => "`&`",
            Self::Pipe => "`|`",
            Self::Caret => "`^`",
            Self::AndAnd => "`&&`",
            Self::OrOr => "`||`",
            Self::LeftParen => "`(`",
            Self::RightParen => "`)`",
            Self::LeftBrace => "`{`",
            Self::RightBrace => "`}`",
            Self::LeftBracket => "`[`",
            Self::RightBracket => "`]`",
            Self::Semicolon => "`;`",
            _ => return None,
        })
    }
}
